homework_00:
  image: data/cherubino.jpg   # путь к изображению
  point: [300, 500]           # x, y координаты точки
  color: [255, 0, 0]          # RGB цвет точки
  radius: 50                  # размеры точки

